[
    {
      "producto": "Paternidad Prenatal - DDC online",
      "pais": "chile",
      "gross_sales": 1350,
      "cost_of_product": -825,
      "cost_of_kit": 0,
      "blood_drawn_sample_handling": -48,
      "sanitary_permits": 0,
      "other_expenses_fedex": 0,
      "physicians_fees": 0,
      "sales_commission": 0,
      "cost_credit_card_pct": "3%",
      "cost_credit_card_usd": -41,
      "cogs": -914,
      "gross_profit": 436,
      "gross_profit_pct": "32%"
    },
    {
      "producto": "Paternidad Prenatal - DDC",
      "pais": "chile",
      "gross_sales": null,
      "cost_of_product": -825,
      "cost_of_kit": 0,
      "blood_drawn_sample_handling": -14,
      "sanitary_permits": 0,
      "other_expenses_fedex": 0,
      "physicians_fees": 0,
      "sales_commission": 0,
      "cost_credit_card_pct": "3%",
      "cost_credit_card_usd": 0,
      "cogs": -839,
      "gross_profit": -839,
      "gross_profit_pct": "0%"
    },
    {
      "producto": "Paternidad Prenatal - BGI online",
      "pais": "chile",
      "gross_sales": 1150,
      "cost_of_product": -670,
      "cost_of_kit": 0,
      "blood_drawn_sample_handling": -28,
      "sanitary_permits": 0,
      "other_expenses_fedex": -16,
      "physicians_fees": 0,
      "sales_commission": 0,
      "cost_credit_card_pct": "3%",
      "cost_credit_card_usd": -35,
      "cogs": -748,
      "gross_profit": 402,
      "gross_profit_pct": "35%"
    },
    {
      "producto": "Paternidad Prenatal - BGI",
      "pais": "chile",
      "gross_sales": 1250,
      "cost_of_product": -670,
      "cost_of_kit": 0,
      "blood_drawn_sample_handling": -28,
      "sanitary_permits": 0,
      "other_expenses_fedex": -16,
      "physicians_fees": 0,
      "sales_commission": 0,
      "cost_credit_card_pct": "3%",
      "cost_credit_card_usd": -38,
      "cogs": -751,
      "gross_profit": 499,
      "gross_profit_pct": "40%"
    },
    {
      "producto": "Sentis Cancer + Discovery (B)",
      "pais": "chile",
      "gross_sales": 2690,
      "cost_of_product": -1800,
      "cost_of_kit": 0,
      "blood_drawn_sample_handling": -14,
      "sanitary_permits": 0,
      "other_expenses_fedex": -16,
      "physicians_fees": 0,
      "sales_commission": -40,
      "cost_credit_card_pct": "3%",
      "cost_credit_card_usd": -81,
      "cogs": -1950,
      "gross_profit": 740,
      "gross_profit_pct": "28%"
    },
    {
      "producto": "Sentis Cancer + Discovery (T)",
      "pais": "chile",
      "gross_sales": 1980,
      "cost_of_product": -1000,
      "cost_of_kit": 0,
      "blood_drawn_sample_handling": -14,
      "sanitary_permits": 0,
      "other_expenses_fedex": -16,
      "physicians_fees": 0,
      "sales_commission": -40,
      "cost_credit_card_pct": "3%",
      "cost_credit_card_usd": -59,
      "cogs": -1129,
      "gross_profit": 851,
      "gross_profit_pct": "43%"
    },
    {
      "producto": "BRC1 BRC2",
      "pais": "chile",
      "gross_sales": 550,
      "cost_of_product": -100,
      "cost_of_kit": 0,
      "blood_drawn_sample_handling": -14,
      "sanitary_permits": 0,
      "other_expenses_fedex": -16,
      "physicians_fees": 0,
      "sales_commission": -20,
      "cost_credit_card_pct": "3%",
      "cost_credit_card_usd": -17,
      "cogs": -166,
      "gross_profit": 384,
      "gross_profit_pct": "70%"
    },
    {
      "producto": "Tempus XT + XR Tejido",
      "pais": "chile",
      "gross_sales": 2600,
      "cost_of_product": -1950,
      "cost_of_kit": 0,
      "blood_drawn_sample_handling": -14,
      "sanitary_permits": 0,
      "other_expenses_fedex": 0,
      "physicians_fees": 0,
      "sales_commission": -40,
      "cost_credit_card_pct": "3%",
      "cost_credit_card_usd": -78,
      "cogs": -2082,
      "gross_profit": 518,
      "gross_profit_pct": "20%"
    },
    {
      "producto": "Tempus xF + biopsia liquida",
      "pais": "chile",
      "gross_sales": 2900,
      "cost_of_product": -1950,
      "cost_of_kit": 0,
      "blood_drawn_sample_handling": -14,
      "sanitary_permits": 0,
      "other_expenses_fedex": 0,
      "physicians_fees": 0,
      "sales_commission": -40,
      "cost_credit_card_pct": "3%",
      "cost_credit_card_usd": -87,
      "cogs": -2091,
      "gross_profit": 809,
      "gross_profit_pct": "28%"
    },
    {
      "producto": "Oncotype Dx Mama",
      "pais": "chile",
      "gross_sales": 3950,
      "cost_of_product": -2171,
      "cost_of_kit": 0,
      "blood_drawn_sample_handling": 0,
      "sanitary_permits": 0,
      "other_expenses_fedex": 0,
      "physicians_fees": 0,
      "sales_commission": -55,
      "cost_credit_card_pct": "3%",
      "cost_credit_card_usd": -119,
      "cogs": -2345,
      "gross_profit": 1606,
      "gross_profit_pct": "41%"
    },
    {
      "producto": "Gen MTHFR",
      "pais": "chile",
      "gross_sales": 750,
      "cost_of_product": -399,
      "cost_of_kit": -1,
      "blood_drawn_sample_handling": -14,
      "sanitary_permits": 0,
      "other_expenses_fedex": -57,
      "physicians_fees": 0,
      "sales_commission": -12,
      "cost_credit_card_pct": "3%",
      "cost_credit_card_usd": -23,
      "cogs": -505,
      "gross_profit": 245,
      "gross_profit_pct": "33%"
    },
    {
      "producto": "Unity Básico",
      "pais": "chile",
      "gross_sales": 450,
      "cost_of_product": -149,
      "cost_of_kit": 0,
      "blood_drawn_sample_handling": -14,
      "sanitary_permits": 0,
      "other_expenses_fedex": 0,
      "physicians_fees": 0,
      "sales_commission": -20,
      "cost_credit_card_pct": "3%",
      "cost_credit_card_usd": -14,
      "cogs": -196,
      "gross_profit": 254,
      "gross_profit_pct": "56%"
    },
    {
      "producto": "Unity Complete",
      "pais": "chile",
      "gross_sales": 850,
      "cost_of_product": -495,
      "cost_of_kit": 0,
      "blood_drawn_sample_handling": -14,
      "sanitary_permits": 0,
      "other_expenses_fedex": 0,
      "physicians_fees": 0,
      "sales_commission": -20,
      "cost_credit_card_pct": "3%",
      "cost_credit_card_usd": -26,
      "cogs": -554,
      "gross_profit": 296,
      "gross_profit_pct": "35%"
    },
    {
      "producto": "Unity Carrier",
      "pais": "chile",
      "gross_sales": 790,
      "cost_of_product": -149,
      "cost_of_kit": 0,
      "blood_drawn_sample_handling": -14,
      "sanitary_permits": 0,
      "other_expenses_fedex": 0,
      "physicians_fees": 0,
      "sales_commission": -20,
      "cost_credit_card_pct": "3%",
      "cost_credit_card_usd": -24,
      "cogs": -206,
      "gross_profit": 584,
      "gross_profit_pct": "74%"
    },
    {
      "producto": "SelectMDX",
      "pais": "chile",
      "gross_sales": 740,
      "cost_of_product": -250,
      "cost_of_kit": 0,
      "blood_drawn_sample_handling": 0,
      "sanitary_permits": 0,
      "other_expenses_fedex": -60,
      "physicians_fees": 0,
      "sales_commission": -30,
      "cost_credit_card_pct": "3%",
      "cost_credit_card_usd": -22,
      "cogs": -362,
      "gross_profit": 378,
      "gross_profit_pct": "51%"
    },
    {
      "producto": "Genomind Professional PGx",
      "pais": "chile",
      "gross_sales": 800,
      "cost_of_product": -475,
      "cost_of_kit": 0,
      "blood_drawn_sample_handling": -34,
      "sanitary_permits": 0,
      "other_expenses_fedex": -60,
      "physicians_fees": 0,
      "sales_commission": -30,
      "cost_credit_card_pct": "3%",
      "cost_credit_card_usd": -24,
      "cogs": -623,
      "gross_profit": 177,
      "gross_profit_pct": "22%"
    },
    {
      "producto": "Genomic Prostate Score",
      "pais": "chile",
      "gross_sales": 3700,
      "cost_of_product": -1810,
      "cost_of_kit": 0,
      "blood_drawn_sample_handling": 0,
      "sanitary_permits": 0,
      "other_expenses_fedex": 0,
      "physicians_fees": 0,
      "sales_commission": -100,
      "cost_credit_card_pct": "3%",
      "cost_credit_card_usd": -111,
      "cogs": -2021,
      "gross_profit": 1679,
      "gross_profit_pct": "45%"
    },
    {
      "producto": "MPS 2.0",
      "pais": "chile",
      "gross_sales": 740,
      "cost_of_product": -250,
      "cost_of_kit": 0,
      "blood_drawn_sample_handling": 0,
      "sanitary_permits": 0,
      "other_expenses_fedex": -50,
      "physicians_fees": 0,
      "sales_commission": -30,
      "cost_credit_card_pct": "4%",
      "cost_credit_card_usd": -30,
      "cogs": -360,
      "gross_profit": 380,
      "gross_profit_pct": "51%"
    },
    {
      "producto": "Mir-THYpe(R)",
      "pais": "chile",
      "gross_sales": 1300,
      "cost_of_product": -850,
      "cost_of_kit": 0,
      "blood_drawn_sample_handling": 0,
      "sanitary_permits": 0,
      "other_expenses_fedex": 0,
      "physicians_fees": 0,
      "sales_commission": -30,
      "cost_credit_card_pct": "3%",
      "cost_credit_card_usd": -39,
      "cogs": -919,
      "gross_profit": 381,
      "gross_profit_pct": "29%"
    },
    {
      "producto": "mirTHYpe FULL",
      "pais": "chile",
      "gross_sales": 1300,
      "cost_of_product": -850,
      "cost_of_kit": 0,
      "blood_drawn_sample_handling": 0,
      "sanitary_permits": 0,
      "other_expenses_fedex": 0,
      "physicians_fees": 0,
      "sales_commission": -30,
      "cost_credit_card_pct": "3%",
      "cost_credit_card_usd": -39,
      "cogs": -919,
      "gross_profit": 381,
      "gross_profit_pct": "29%"
    },
    {
      "producto": "mirTHYpe preOp",
      "pais": "chile",
      "gross_sales": 800,
      "cost_of_product": -470,
      "cost_of_kit": 0,
      "blood_drawn_sample_handling": 0,
      "sanitary_permits": 0,
      "other_expenses_fedex": 0,
      "physicians_fees": 0,
      "sales_commission": -30,
      "cost_credit_card_pct": "3%",
      "cost_credit_card_usd": -24,
      "cogs": -524,
      "gross_profit": 276,
      "gross_profit_pct": "35%"
    },
    {
      "producto": "MirThype Target",
      "pais": "chile",
      "gross_sales": 1390,
      "cost_of_product": -850,
      "cost_of_kit": 0,
      "blood_drawn_sample_handling": 0,
      "sanitary_permits": 0,
      "other_expenses_fedex": 0,
      "physicians_fees": 0,
      "sales_commission": -30,
      "cost_credit_card_pct": "3%",
      "cost_credit_card_usd": -42,
      "cogs": -922,
      "gross_profit": 468,
      "gross_profit_pct": "34%"
    },
    {
      "producto": "MaterniT21",
      "pais": "chile",
      "gross_sales": null,
      "cost_of_product": null,
      "cost_of_kit": 0,
      "blood_drawn_sample_handling": -14,
      "sanitary_permits": 0,
      "other_expenses_fedex": 0,
      "physicians_fees": 0,
      "sales_commission": 0,
      "cost_credit_card_pct": "3%",
      "cost_credit_card_usd": 0,
      "cogs": -14,
      "gross_profit": -14,
      "gross_profit_pct": "0%"
    },
    {
      "producto": "MaterniT21 Plus",
      "pais": "chile",
      "gross_sales": 550,
      "cost_of_product": -295,
      "cost_of_kit": 0,
      "blood_drawn_sample_handling": null,
      "sanitary_permits": 0,
      "other_expenses_fedex": 0,
      "physicians_fees": 0,
      "sales_commission": 0,
      "cost_credit_card_pct": "3%",
      "cost_credit_card_usd": -17,
      "cogs": null,
      "gross_profit": null,
      "gross_profit_pct": null
    },
    {
      "producto": "MATERNIT 21 + SCA",
      "pais": "chile",
      "gross_sales": null,
      "cost_of_product": null,
      "cost_of_kit": 0,
      "blood_drawn_sample_handling": -14,
      "sanitary_permits": 0,
      "other_expenses_fedex": 0,
      "physicians_fees": 0,
      "sales_commission": 0,
      "cost_credit_card_pct": "3%",
      "cost_credit_card_usd": 0,
      "cogs": -14,
      "gross_profit": -14,
      "gross_profit_pct": "0%"
    },
    {
      "producto": "MATERNIT 21 + SCA + ESS",
      "pais": "chile",
      "gross_sales": null,
      "cost_of_product": null,
      "cost_of_kit": 0,
      "blood_drawn_sample_handling": -14,
      "sanitary_permits": 0,
      "other_expenses_fedex": 0,
      "physicians_fees": 0,
      "sales_commission": 0,
      "cost_credit_card_pct": "3%",
      "cost_credit_card_usd": 0,
      "cogs": -14,
      "gross_profit": -14,
      "gross_profit_pct": "0%"
    },
    {
      "producto": "MATERNIT GENOME",
      "pais": "chile",
      "gross_sales": 890,
      "cost_of_product": -595,
      "cost_of_kit": 0,
      "blood_drawn_sample_handling": -14,
      "sanitary_permits": 0,
      "other_expenses_fedex": 0,
      "physicians_fees": 0,
      "sales_commission": 0,
      "cost_credit_card_pct": "3%",
      "cost_credit_card_usd": -27,
      "cogs": -635,
      "gross_profit": 255,
      "gross_profit_pct": "29%"
    },
    {
      "producto": "Vista Carrier 1200",
      "pais": "chile",
      "gross_sales": 990,
      "cost_of_product": -499,
      "cost_of_kit": 0,
      "blood_drawn_sample_handling": -14,
      "sanitary_permits": 0,
      "other_expenses_fedex": 0,
      "physicians_fees": 0,
      "sales_commission": 0,
      "cost_credit_card_pct": "3%",
      "cost_credit_card_usd": -30,
      "cogs": -542,
      "gross_profit": 448,
      "gross_profit_pct": "45%"
    },
    {
      "producto": "Vista Carrier 1200 - 2 pax",
      "pais": "chile",
      "gross_sales": 1600,
      "cost_of_product": -1000,
      "cost_of_kit": 0,
      "blood_drawn_sample_handling": -28,
      "sanitary_permits": 0,
      "other_expenses_fedex": 0,
      "physicians_fees": 0,
      "sales_commission": 0,
      "cost_credit_card_pct": "3%",
      "cost_credit_card_usd": -48,
      "cogs": -1076,
      "gross_profit": 524,
      "gross_profit_pct": "33%"
    },
    {
      "producto": "Vista Targeted Carrier",
      "pais": "chile",
      "gross_sales": 550,
      "cost_of_product": -200,
      "cost_of_kit": 0,
      "blood_drawn_sample_handling": -14,
      "sanitary_permits": 0,
      "other_expenses_fedex": 0,
      "physicians_fees": 0,
      "sales_commission": 0,
      "cost_credit_card_pct": "3%",
      "cost_credit_card_usd": -17,
      "cogs": -230,
      "gross_profit": 320,
      "gross_profit_pct": "58%"
    },
    {
      "producto": "Vista Targeted Carrier - 2 pax",
      "pais": "chile",
      "gross_sales": 990,
      "cost_of_product": -400,
      "cost_of_kit": 0,
      "blood_drawn_sample_handling": -28,
      "sanitary_permits": 0,
      "other_expenses_fedex": 0,
      "physicians_fees": 0,
      "sales_commission": 0,
      "cost_credit_card_pct": "3%",
      "cost_credit_card_usd": -30,
      "cogs": -457,
      "gross_profit": 533,
      "gross_profit_pct": "54%"
    },
    {
      "producto": "Envíos",
      "pais": "chile",
      "gross_sales": null,
      "cost_of_product": null,
      "cost_of_kit": null,
      "blood_drawn_sample_handling": null,
      "sanitary_permits": null,
      "other_expenses_fedex": null,
      "physicians_fees": 0,
      "sales_commission": 0,
      "cost_credit_card_pct": null,
      "cost_credit_card_usd": null,
      "cogs": 0,
      "gross_profit": 0,
      "gross_profit_pct": "0%"
    },
    {
      "producto": "Afirma GSC",
      "pais": "chile",
      "gross_sales": 2500,
      "cost_of_product": -1250,
      "cost_of_kit": 0,
      "blood_drawn_sample_handling": 0,
      "sanitary_permits": 0,
      "other_expenses_fedex": -57,
      "physicians_fees": 0,
      "sales_commission": -40,
      "cost_credit_card_pct": "3%",
      "cost_credit_card_usd": -75,
      "cogs": -1422,
      "gross_profit": 1078,
      "gross_profit_pct": "43%"
    },
    {
      "producto": "Cxbladder",
      "pais": "chile",
      "gross_sales": 990,
      "cost_of_product": -400,
      "cost_of_kit": 0,
      "blood_drawn_sample_handling": -14,
      "sanitary_permits": 0,
      "other_expenses_fedex": -57,
      "physicians_fees": 0,
      "sales_commission": 0,
      "cost_credit_card_pct": "3%",
      "cost_credit_card_usd": -30,
      "cogs": -501,
      "gross_profit": 489,
      "gross_profit_pct": "49%"
    },
    {
      "producto": "4Kscore",
      "pais": "chile",
      "gross_sales": 790,
      "cost_of_product": -395,
      "cost_of_kit": 0,
      "blood_drawn_sample_handling": -14,
      "sanitary_permits": 0,
      "other_expenses_fedex": -57,
      "physicians_fees": 0,
      "sales_commission": 0,
      "cost_credit_card_pct": "3%",
      "cost_credit_card_usd": -24,
      "cogs": -490,
      "gross_profit": 300,
      "gross_profit_pct": "38%"
    },
    {
      "producto": "ErComplete",
      "pais": "chile",
      "gross_sales": null,
      "cost_of_product": -775,
      "cost_of_kit": 0,
      "blood_drawn_sample_handling": -14,
      "sanitary_permits": 0,
      "other_expenses_fedex": -57,
      "physicians_fees": 0,
      "sales_commission": 0,
      "cost_credit_card_pct": "3%",
      "cost_credit_card_usd": 0,
      "cogs": -846,
      "gross_profit": -846,
      "gross_profit_pct": "0%"
    },
    {
      "producto": "ErPeak",
      "pais": "chile",
      "gross_sales": null,
      "cost_of_product": -425,
      "cost_of_kit": 0,
      "blood_drawn_sample_handling": -14,
      "sanitary_permits": 0,
      "other_expenses_fedex": -57,
      "physicians_fees": 0,
      "sales_commission": 0,
      "cost_credit_card_pct": "3%",
      "cost_credit_card_usd": 0,
      "cogs": -496,
      "gross_profit": -496,
      "gross_profit_pct": "0%"
    },
    {
      "producto": "ImmunoCAP ISAC",
      "pais": "chile",
      "gross_sales": null,
      "cost_of_product": -240,
      "cost_of_kit": 0,
      "blood_drawn_sample_handling": -14,
      "sanitary_permits": 0,
      "other_expenses_fedex": -57,
      "physicians_fees": 0,
      "sales_commission": 0,
      "cost_credit_card_pct": "3%",
      "cost_credit_card_usd": 0,
      "cogs": -311,
      "gross_profit": -311,
      "gross_profit_pct": "0%"
    },
    {
      "producto": "Invitae Multi-Cancer Panel",
      "pais": "chile",
      "gross_sales": 780,
      "cost_of_product": -349,
      "cost_of_kit": 0,
      "blood_drawn_sample_handling": -14,
      "sanitary_permits": 0,
      "other_expenses_fedex": -57,
      "physicians_fees": 0,
      "sales_commission": 0,
      "cost_credit_card_pct": "3%",
      "cost_credit_card_usd": -23,
      "cogs": -444,
      "gross_profit": 336,
      "gross_profit_pct": "43%"
    },
    {
      "producto": "Invitae Panel Ca Prostata",
      "pais": "chile",
      "gross_sales": 700,
      "cost_of_product": -150,
      "cost_of_kit": 0,
      "blood_drawn_sample_handling": -14,
      "sanitary_permits": 0,
      "other_expenses_fedex": -57,
      "physicians_fees": 0,
      "sales_commission": 0,
      "cost_credit_card_pct": "3%",
      "cost_credit_card_usd": -21,
      "cogs": -242,
      "gross_profit": 458,
      "gross_profit_pct": "65%"
    }
  ]